language: ruby
sudo: false

cache:
  bundler: true

dist: trusty

rvm:
  - 2.3
  - 2.4
  - 2.2.2

before_install:
  - gem install bundler

install:
  - bundle install --jobs=3 --retry=3
  # bibtex2html
  - wget --no-check-certificate http://www.lri.fr/\~filliatr/ftp/bibtex2html/bibtex2html-1.98-linux.tar.gz
  - tar xvfz bibtex2html-1.98-linux.tar.gz
  - cp -v bibtex2html-1.98-linux/* ~/bin
  - rm -rf bibtex2html-1.98-linux bibtex2html-1.98-linux.tar.gz
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
