url:
baseurl:
timezone: Etc/UTC

sass:
  sass_dir: public/css
  style: :compressed

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll/scholar

jekyll-archives:
  enabled:
    - tags
  layouts:
    year: year-archives
    tag: tag-archives
    category: category-archives
    month: month-archives
    day: day-archives
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'


permalink:     /:categories/:title.html

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

scholar:
  style: _bibliography/style.csl
  bibliography: pubs.bib
  bibliography_template: bibtemplate
  bibliography_list_tag: dd
  query: "@*"
  sort_by: year,month
  order: descending

jekyll-minifier:
  exclude: 'feed.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
